name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make linux
      - name: testing binary
        run: ./template-lib_cpp20
  
  build-windows:
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: checking source files
        run: ls
        run: ls src
      - name: build
        run: make windows
      - name: testing binary
        run: ./template-lib_cpp20.exe
